# Generated by Django 6.0.6 on 2026-06-29 04:51

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_heading_slug_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.blog.models.blog_thumbnail_directory),
        ),
    ]
